version: '3.7'

services:

  users:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@pt-db:5432/persons_tasks
    depends_on:
      - pt-db

  pt-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
